Dockerfile
# Dockerfile.server

# Указываем базовый образ Node.js
FROM node:16

# Устанавливаем рабочую директорию внутри контейнера
WORKDIR /usr/src/app

# Копируем package.json и package-lock.json
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем остальные файлы серверного приложения
COPY . .

# Открываем порт, на котором будет работать серверное приложение
EXPOSE 3000


# Команда, которая будет выполняться при запуске контейнера
CMD [ "npm", "start" ]